### ISSUE TITLE
Loading npm modules from inside vue files

### ISSUE THREAD

**Issue by happyCoda** [nblackburn/vue-brunch#22] opened 2017-05-20 22:23 UTC
I've encounter a problem when attempting to import an npm module from my .vue files. Here is my brunch config:
```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'js/bundle.js': /^app\/js|(.|\/)*node_modules/
      }
    },
    stylesheets: {
      joinTo: 'css/bundle.css'
    }
  },
  modules: {
    autoRequire: {
      'js/bundle.js': ['js/main']
    }
  }
};
```

and this is a module:
```javascript
<template lang="html">
  <div class="list-wrapper">
    <ul class="list">
      <li v-for="book in list">{{book.title}}</li>
    </ul>
  </div>
</template>

<script>
  import _ from 'lodash';
  
  export default {
    name: 'BookList',
    data() {
      return {
        list: [
          {
            title: `You Don't Know JS: ES6 & Beyond`,
            author: `Kyle Simpson`,
            year: 2015
          },
          {
            title: `Secrets of the JavaScript Ninja`,
            author: [`John Resig`, `Bear Bibeault`, `Josip Maras`],
            year: 2014
          }
        ]
      }
    },
    computed: {
      newest() {
        return _(this.list).filter((item) => {
          return item.year > 2014;
        }).value();
      }
    }
  }
</script>

<style lang="less">
</style>
```
I compile this stuff and get this error in Chrome console:

`bundle.js:61 Uncaught Error: Cannot find module 'lodash' from 'js/components/book-list.vue'`.

When I looked at bundle.js file I discovered that lodash module has not been included in the bundle. However, if I import lodash module in my main.js file, import in vue component start working and lodash includes in the bundle. It seems like vue-brunch (and vueify under the hood) just compile .vue files and inserts resulting js into bundle without resolving it's dependencies.

I am using brunch@2.10.9, vue-brunch@2.0.1 and vue@2.3.3

**Comment by nicooga** [comment] 2017-06-02 20:27
Take a look at https://github.com/nblackburn/vue-brunch/issues/6. I think it's a duplicate.

**Comment by happyCoda** [comment] 2017-06-02 20:54
@nicooga, yep, I know about that issue, but it has been closed despite the problem did not solved.

**Comment by emendelski** [comment] 2017-06-26 11:42
Any news in this thread?

**Comment by happyCoda** [comment] 2017-06-26 16:11
@emendelski looks like project is unmaintained. @nblackburn can you shed some light here?

**Comment by nblackburn** [comment] 2017-06-26 16:19
@happyCoda Hey, i originally created this project as a quick solution to getting Vue support in Brunch. 

I have since moved to webpack for all of my projects so unfortunatly i have not really been maintaining this project.

**Comment by happyCoda** [comment] 2017-06-26 16:23
@nblackburn that's sad, but thanks anyway!

**Comment by happyCoda** [comment] 2017-06-26 16:25
btw, can you point this in README?

**Comment by nblackburn** [comment] 2017-06-26 17:40
@happyCoda Once i have decided what i am doing with this project then i will let everyone know but as it stands i am uncertain of the projects future.

**Comment by theocodes** [comment] 2017-07-17 18:46
@happyCoda I've taken over the project and will be looking at addressing this as soon as I get a chance. Just an FYI :)

**Comment by bobmanary** [comment] 2017-11-10 22:51
I think this should be fixable by changing `VueBrunch.prototype.type = 'template';` to `'javascript'`. I'm not sure if there are any other problems caused by this but it appears to work for me.

I guess there was a design decision by the Brunch people to not analyze the output of 'template' plugins for imports, but it works when importing other templates because it bundles all of the app directory by default.

**Comment by kwando** [comment] 2017-11-29 14:27
Any news on this? :)

**Comment by samuelgozi** [comment] 2017-11-30 17:14
If anyone has a solution for this, Please share!

**Comment by elkelk** [comment] 2017-12-19 15:16
I have a similar issue where I cannot access Object, Array, or JSON objects within a class in a .vue file. Changing `VueBrunch.prototype.type = 'javascript';` also works for me. It seems like a change that should be made.

**Comment by elkelk** [comment] 2018-01-03 18:57
Any maintainers interested in merging #35 to close this bug?

**Comment by nblackburn** [comment] 2018-01-03 19:18
@elkelk I would like to apologize for for the lack of activity on here, i will touch base with @theocodes and see what is going on.

**Comment by elkelk** [comment] 2018-01-03 19:27
No worries! Thanks for pushing it forward.

**Comment by theocodes** [comment] 2018-01-03 19:31
Hi all, sorry for the absence but I've too much on my plate at the moment and am unable to address any issues. I'm happy to pass the torch to someone else interested or back to @nblackburn if you like?

Thanks

**Comment by elkelk** [comment] 2018-01-03 19:43
You can add me as a contributor and between the three of us, we can maybe keep this thing alive?

**Comment by nblackburn** [comment] 2018-01-04 00:28
I have contacted @theocodes offering ownership to be transferred back to me and await a reply.

**Closed** 2018-01-04 16:37 UTC
Labels: bug

**Comment by ahmetabdi** [comment] 2018-01-18 13:14
Still a issue but got closed 🤔

**Comment by nblackburn** [comment] 2018-01-18 13:16
@ahmetabdi it's been fixed but not published.

**Comment by ahmetabdi** [comment] 2018-01-18 13:25
Ah I see
